[tools]
node = "latest"
python = "latest"
bat = "latest"
curlie = "latest"
delta = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
pandoc = "latest"
rg = "latest"
shellcheck = "latest"
shfmt = "latest"
qsv = "latest"
cookiecutter = "latest"
httpie-go = "latest"
